/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SimulationAndReport;
import javax.swing.*;
import java.awt.*;
import java.util.List;
/**
 *
 * @author 70787
 */
public class BarChartPanel extends javax.swing.JPanel {

    public static class Item {
        public final String label;
        public final double value;
        public Item(String label, double value) {
            this.label = label;
            this.value = value;
        }
    }

    private java.util.List<Item> data;
    private String title = "Top Impact (Δ Revenue)";

    public void setData(java.util.List<Item> data) {
        this.data = data;
        repaint();
    }
    public void setTitle(String t) {
        this.title = t;
        repaint();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);

        if (data == null || data.isEmpty()) {
            g.drawString("No data. Run simulation first.", 12, 20);
            return;
        }

        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
        g2.setRenderingHint(
                java.awt.RenderingHints.KEY_ANTIALIASING,
                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        int w = getWidth();
        int h = getHeight();

        int pad = 48;
        int top = 40;
        int bottom = 48;

        int chartW = Math.max(1, w - pad * 2);
        int chartH = Math.max(1, h - top - bottom);

        g2.setFont(getFont().deriveFont(java.awt.Font.BOLD, 14f));
        g2.drawString(title, pad, 22);

        double maxAbs = 1.0;
        for (Item it : data) maxAbs = Math.max(maxAbs, Math.abs(it.value));

        int n = data.size();
        int gap = 8;
        int barW = Math.max(10, (chartW - gap * Math.max(0, n - 1)) / Math.max(1, n));
        int x = pad;

        int baseY = top + chartH; 
        g2.setFont(getFont().deriveFont(11f));

        for (Item it : data) {
            int barH = (int) Math.round(Math.abs(it.value) / maxAbs * (chartH - 20));
            int y = top + (chartH - barH);

            g2.fillRect(x, y, barW, barH);

            String val = String.format("%.0f", it.value);
            g2.drawString(val, x, y - 4);

            String lab = it.label == null ? "" : it.label;
            if (lab.length() > 12) lab = lab.substring(0, 12) + "…";
            int sw = g2.getFontMetrics().stringWidth(lab);
            g2.drawString(lab, x + Math.max(0, (barW - sw) / 2), baseY + 16);

            x += barW + gap;
        }
    }
    /**
     * Creates new form BarChartPanel
     */
    public BarChartPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
