/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SimulationAndReport;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;
/**
 *
 * @author 70787
 */
public class MainUI extends javax.swing.JFrame {
    
    
    private final TheBusiness.Business.Business business;
    private SimulationAndReport.SimulationResult lastResult;
    private final SimulationAndReport.BarChartPanel chartPanel = new SimulationAndReport.BarChartPanel();

    // Add this no-arg constructor anywhere in the class body, outside generated blocks


    public MainUI(TheBusiness.Business.Business b) {
        this.business = b;
        initComponents();
        chartHolder.setLayout(new java.awt.BorderLayout());
        chartHolder.add(chartPanel, java.awt.BorderLayout.CENTER);
    }
    public MainUI() {
        this.business = null; 
        initComponents();
        chartHolder.setLayout(new java.awt.BorderLayout());
        chartHolder.add(chartPanel, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        tabTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        tabChart = new javax.swing.JPanel();
        chartHolder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBrowseProducts = new javax.swing.JButton();
        btnRunSimulation = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        javax.swing.GroupLayout tabTableLayout = new javax.swing.GroupLayout(tabTable);
        tabTable.setLayout(tabTableLayout);
        tabTableLayout.setHorizontalGroup(
            tabTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabTableLayout.setVerticalGroup(
            tabTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTableLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabMain.addTab("Table", tabTable);

        javax.swing.GroupLayout chartHolderLayout = new javax.swing.GroupLayout(chartHolder);
        chartHolder.setLayout(chartHolderLayout);
        chartHolderLayout.setHorizontalGroup(
            chartHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        chartHolderLayout.setVerticalGroup(
            chartHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tabChartLayout = new javax.swing.GroupLayout(tabChart);
        tabChart.setLayout(tabChartLayout);
        tabChartLayout.setHorizontalGroup(
            tabChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabChartLayout.setVerticalGroup(
            tabChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabChartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabMain.addTab("Chart", tabChart);

        btnBrowseProducts.setText("Browse Products");
        btnBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseProductsActionPerformed(evt);
            }
        });

        btnRunSimulation.setText("Run Simulation");
        btnRunSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunSimulationActionPerformed(evt);
            }
        });

        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBrowseProducts)
                .addGap(119, 119, 119)
                .addComponent(btnRunSimulation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReport)
                    .addComponent(btnRunSimulation)
                    .addComponent(btnBrowseProducts))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProductsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m = new DefaultTableModel(new Object[]{"Product","Target","Floor","Ceiling"}, 0);
        for (Supplier s : business.getSupplierDirectory().getSuplierList()) {
            for (Product p : s.getProductCatalog().getProductList()) {
                m.addRow(new Object[]{p.toString(), p.getTargetPrice(), p.getFloorPrice(), p.getCeilingPrice()});
            }
        }
        tblProducts.setModel(m);
        tabMain.setSelectedComponent(tabTable);
    }//GEN-LAST:event_btnBrowseProductsActionPerformed

    private void btnRunSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunSimulationActionPerformed
        // TODO add your handling code here:
        SimulationEngine engine = new SimulationEngine(business);
        lastResult = engine.runSimulation();

        DefaultTableModel m = new DefaultTableModel(
            new Object[]{"Product","Rev Before","Rev After","Δ","RateAbove"}, 0);
        java.util.List<BarChartPanel.Item> list = new java.util.ArrayList<>();

        for (Supplier s : business.getSupplierDirectory().getSuplierList()) {
            for (Product p : s.getProductCatalog().getProductList()) {
                double before = lastResult.revenueBefore.getOrDefault(p, 0.0);
                double after  = lastResult.revenueAfter .getOrDefault(p, 0.0);
                double delta  = after - before;
                double rate   = lastResult.salesFreq.getOrDefault(p, new Frequency()).rateAbove();

                m.addRow(new Object[]{p.toString(),
                        String.format("%.2f", before),
                        String.format("%.2f", after),
                        String.format("%.2f", delta),
                        String.format("%.2f", rate)});
                list.add(new BarChartPanel.Item(p.toString(), delta));
            }
        }
        m.addRow(new Object[]{"TOTAL",
            String.format("%.2f", lastResult.totalBefore),
            String.format("%.2f", lastResult.totalAfter),
            String.format("%.2f", (lastResult.totalAfter - lastResult.totalBefore)),
            ""});
        tblProducts.setModel(m);

        list.sort((a,b)->Double.compare(Math.abs(b.value), Math.abs(a.value)));
        chartPanel.setData(list.size()>10 ? list.subList(0,10) : list);
        tabMain.setSelectedComponent(tabChart);

        if (lastResult.mostImpactProduct != null) {
            JOptionPane.showMessageDialog(this,
                "Most Impact: " + lastResult.mostImpactProduct.toString()
                + " |Δ|=" + String.format("%.2f", lastResult.maxDelta));
        }
    }//GEN-LAST:event_btnRunSimulationActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        // TODO add your handling code here:
        if (lastResult == null) { JOptionPane.showMessageDialog(this,"please run model"); return; }
        try {
            JFileChooser fc = new JFileChooser();
            fc.setSelectedFile(new java.io.File("final_report.csv"));
            if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                java.io.File out = new ReportGenerator().generateFinalReport(
                        lastResult, fc.getSelectedFile().getAbsolutePath());
                JOptionPane.showMessageDialog(this, "success：\n"+out.getAbsolutePath());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "failed："+ex.getMessage());
        }
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseProducts;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnRunSimulation;
    private javax.swing.JPanel chartHolder;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tabChart;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JPanel tabTable;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
